name: Test

on: ['pull_request', 'push']

env:
  FORCE_COLOR: 1

jobs:
  jest:
    name: Jest
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Setup Jest
        run: |
          npm install --save-dev jest babel-jest @babel/core @babel/preset-env
      - name: Jest Report
        run: npx jest